// quotes.dart

List<String> quotes = [
  "Age is an issue of mind over matter. If you don't mind, it doesn't matter. - Mark Twain",
  "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
  "The only way to do great work is to love what you do. - Steve Jobs",
  "The best way to predict the future is to create it. - Abraham Lincoln",
  "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
  "Believe you can and you're halfway there. - Theodore Roosevelt",
  "It does not matter how slowly you go as long as you do not stop. - Confucius",
  "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
  "The journey of a thousand miles begins with one step. - Lao Tzu",
  "Optimism is the faith that leads to achievement. Nothing can be done without hope and confidence. - Helen Keller",
  "You are never too old to set another goal or to dream a new dream. - Les Brown",
  "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
  "The biggest risk is not taking any risk. In a world that is changing quickly, the only strategy that is guaranteed to fail is not taking risks. - Mark Zuckerberg",
  "Happiness is not something you postpone for the future; it is something you design for the present. - Jim Rohn",
  "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
  "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
  "The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack in will. - Vince Lombardi",
  "Success is stumbling from failure to failure with no loss of enthusiasm. - Winston S. Churchill",
  "I can't change the direction of the wind, but I can adjust my sails to always reach my destination. - Jimmy Dean",
  "Do not wait to strike till the iron is hot, but make it hot by striking. - William Butler Yeats",
  "The only person you should try to be better than is the person you were yesterday. - Anonymous",
  "It's not what happens to you, but how you react to it that matters. - Epictetus",
  "Success is not how high you have climbed, but how you make a positive difference to the world. - Roy T. Bennett",
  "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
  "The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it. - Jordan Belfort",
  "You don't have to be great to start, but you have to start to be great. - Zig Ziglar",
  "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
  "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
  "The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack in will. - Vince Lombardi",
  "Success is stumbling from failure to failure with no loss of enthusiasm. - Winston S. Churchill",
  "I can't change the direction of the wind, but I can adjust my sails to always reach my destination. - Jimmy Dean",
  "Do not wait to strike till the iron is hot, but make it hot by striking. - William Butler Yeats",
  "The only person you should try to be better than is the person you were yesterday. - Anonymous",
  "It's not what happens to you, but how you react to it that matters. - Epictetus",
  "Success is not how high you have climbed, but how you make a positive difference to the world. - Roy T. Bennett",
  "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
  "The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it. - Jordan Belfort",
  "You don't have to be great to start, but you have to start to be great. - Zig Ziglar",
  "The only way to do great work is to love what you do. - Steve Jobs",
  "The best way to predict the future is to create it. - Abraham Lincoln",
  "Believe you can and you're halfway there. - Theodore Roosevelt",
  "It does not matter how slowly you go as long as you do not stop. - Confucius",
  "Optimism is the faith that leads to achievement. Nothing can be done without hope and confidence. - Helen Keller",
  "The journey of a thousand miles begins with one step. - Lao Tzu",
  "Age is an issue of mind over matter. If you don't mind, it doesn't matter. - Mark Twain",
  "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
  "The only way to do great work is to love what you do. - Steve Jobs",
  "The best way to predict the future is to create it. - Abraham Lincoln",
  "Believe you can and you're halfway there. - Theodore Roosevelt",
  "It does not matter how slowly you go as long as you do not stop. - Confucius",
  "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
  "The journey of a thousand miles begins with one step. - Lao Tzu",
  "Optimism is the faith that leads to achievement. Nothing can be done without hope and confidence. - Helen Keller",
  "You are never too old to set another goal or to dream a new dream. - Les Brown",
  "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
  "The biggest risk is not taking any risk. In a world that is changing quickly, the only strategy that is guaranteed to fail is not taking risks. - Mark Zuckerberg",
  "Happiness is not something you postpone for the future; it is something you design for the present. - Jim Rohn",
  "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
  "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
  "The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack in will. - Vince Lombardi",
  "Success is stumbling from failure to failure with no loss of enthusiasm. - Winston S. Churchill",
  "I can't change the direction of the wind, but I can adjust my sails to always reach my destination. - Jimmy Dean",
  "Do not wait to strike till the iron is hot, but make it hot by striking. - William Butler Yeats",
  "The only person you should try to be better than is the person you were yesterday. - Anonymous",
  "It's not what happens to you, but how you react to it that matters. - Epictetus",
  "Success is not how high you have climbed, but how you make a positive difference to the world. - Roy T. Bennett",
  "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
  "The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it. - Jordan Belfort",
  "You don't have to be great to start, but you have to start to be great. - Zig Ziglar",
  "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
  "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
  "The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack in will. - Vince Lombardi",
  "Success is stumbling from failure to failure with no loss of enthusiasm. - Winston S. Churchill",
  "I can't change the direction of the wind, but I can adjust my sails to always reach my destination. - Jimmy Dean",
  "Do not wait to strike till the iron is hot, but make it hot by striking. - William Butler Yeats",
  "The only person you should try to be better than is the person you were yesterday. - Anonymous",
  "It's not what happens to you, but how you react to it that matters. - Epictetus",
  "Success is not how high you have climbed, but how you make a positive difference to the world. - Roy T. Bennett",
];
