// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpZKPNo5wgg3aTby3ksiCdzIbhHQAcdtM',
    appId: '1:65215985571:web:a93b753b410fe5fd80cc16',
    messagingSenderId: '65215985571',
    projectId: 'seniorshieldapp-a65aa',
    authDomain: 'seniorshieldapp-a65aa.firebaseapp.com',
    storageBucket: 'seniorshieldapp-a65aa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhU-h4l0ZrpXwVFkbNMIJcph4ZQ_k4HVw',
    appId: '1:65215985571:android:41c01de3d34bf5dc80cc16',
    messagingSenderId: '65215985571',
    projectId: 'seniorshieldapp-a65aa',
    storageBucket: 'seniorshieldapp-a65aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsbSPMxTTPj23EBv9bGiWy74ps_MJvAiY',
    appId: '1:65215985571:ios:978f06716f15d44580cc16',
    messagingSenderId: '65215985571',
    projectId: 'seniorshieldapp-a65aa',
    storageBucket: 'seniorshieldapp-a65aa.appspot.com',
    iosBundleId: 'com.example.seniorshield',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsbSPMxTTPj23EBv9bGiWy74ps_MJvAiY',
    appId: '1:65215985571:ios:978f06716f15d44580cc16',
    messagingSenderId: '65215985571',
    projectId: 'seniorshieldapp-a65aa',
    storageBucket: 'seniorshieldapp-a65aa.appspot.com',
    iosBundleId: 'com.example.seniorshield',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpZKPNo5wgg3aTby3ksiCdzIbhHQAcdtM',
    appId: '1:65215985571:web:b7ead7052adfe3c580cc16',
    messagingSenderId: '65215985571',
    projectId: 'seniorshieldapp-a65aa',
    authDomain: 'seniorshieldapp-a65aa.firebaseapp.com',
    storageBucket: 'seniorshieldapp-a65aa.appspot.com',
  );
}
